dado = input('Digite algo: ')
print('O tipo primitivo é: ', type(dado))
print('Só tem espaços? {}'.format(dado.isspace()) )
print('É um número? {}'.format(dado.isnumeric()) )
print('É alphabético? {}'.format(dado.isalpha()) )
print('É alfanumérico? {}'.format(dado.isalnum()))
print('Está em maiúsculas? {}'.format(dado.isupper()))
print('Está em minúsculas? {}'.format(dado.islower()))
print('Está capitalizada? {}'.format(dado.istitle()))